# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 930f33abde880f49e2930ef922f061e8a37184fb8c08b0d6a44317c3cc39c0cb0cbbc8da309082c620432342b4ec18c26d60adc7d2c8f58094d7c07dcef22cbf

test:
  secret_key_base: 0d8e3c3e818ba18dbe542f6f8a2131925f30ff0bbdc87ede2fb8ba36abb0bb40b23c17e04c3a9aed2aacfe818e585ac109f42049a621c13af3ec35d23c19d02a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
